name: C Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Make
        run: make

      - name: Run (with dummy input)
        # Создаем пустой ввод, чтобы scanf не завис
        run: echo "Name Fac 101 01 01 2023" | ./main
